### ISSUE TITLE
Having selected multiple file, editor open them as multiple buffers

### ISSUE THREAD

**Issue by mizhozan** [saccarosium/shell-velocity#2]
Thanks for this script. It's very useful and application independet.

Is it possible to use `--multi` with fuzzy select. I tested with this:
```
export SHV_PICKER="fzf -m --ansi --print-query --bind=alt-enter:print-query"
```

and while the fzf multi select work in fzf window the shv only open the last one in vim. Is there a way to handle multiple selection?

**Comment by saccarosium** [comment]
> Is there a way to handle multiple selection?

Not yet, but I'm working on it. There are a little complexities that needs to be addressed, but should be doable.

**Comment by saccarosium** [comment]
Added and should work. Thanks for the suggestions!

**Comment by mizhozan** [comment]
> Added and should work. Thanks for the suggestions!

Awesome, it works perfect! Thanks
