### ISSUE TITLE
replace by user set grepper

### ISSUE THREAD

**Issue by Konfekt** [saccarosium/shell-velocity#8]
Thank you for this useful tool! Would it not be sensible (or maybe rather overkill?) to use a common grepper such as ripgrep (as in https://github.com/alok/notational-fzf-vim) and fall back to grep to implement https://github.com/saccarosium/shell-velocity/blob/f84beddce472d9f6cbdece923fa64b6cdca1152a/shv#L87 ?

**Comment by saccarosium** [comment]
It is probably better I expose a variable to change the grep command. With a little of logic to use ripgrep if available.
