### ISSUE TITLE
key bind to create note when grepping

### ISSUE THREAD

**Issue by Konfekt** [saccarosium/shell-velocity#9]
When using `shv g` how about a fzf key binding (such as `Ctrl-X` as in https://github.com/alok/notational-fzf-vim) to create a new note with the search query `{q}` as a title ?

**Comment by saccarosium** [comment]
Hi @Konfekt,
There is already a binding for this, is `Alt-Enter`. Perhaps i should document it better.

**Comment by Konfekt** [comment]
Yes, either one clones the huge repo with the man/doc files, or the shell script and github page itself rest rather mute

**Comment by Konfekt** [comment]
Can this bind be configured? For terminals using `.Xresources` such as xterm or urxvt, it is already bound otherwise; on Konsole it works ok.

**Comment by Konfekt** [comment]
Sorry for the noise, I see that it is already exposed as `$SHV_PICKER` at https://github.com/saccarosium/shell-velocity/blob/934bed3698c1bb43411662aefea0355a5c7639d1/shv#L12
